In [1]:
import numpy as np

In [2]:
#1. Create a NumPy array of 10 zeros.
#Hint: Use np.zeros()
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#2. Create a 1D NumPy array of integers from 10 to 49.
#Hint: Use np.arange()

np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
#3. Reverse the array you created in Exercise 2.
#Hint: Use slicing

a = np.arange(10, 50)
a[::-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
#Create a 3x3 matrix with values from 0 to 8.
#Hint: Use reshape()

b = np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#5. Find the indices of non-zero elements in [1, 2, 0, 0, 4, 0].
#Hint: Use np.nonzero()

a = np.asarray([1, 2, 0, 0, 4, 0])
np.nonzero(a)

(array([0, 1, 4]),)

In [14]:
#6. Create a 5x5 identity matrix.
#Hint: Use np.eye()

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#7. Create a 3x3x3 array with random values.
#Hint: Use np.random.random()

a = np.asarray([np.random.random() for _ in range(27) ]).reshape(3,3,3)
print(a)

#OR

a_using_rand = np.random.random((3,3,3))
print(a_using_rand)

[[[0.99998252 0.88363851 0.87271639]
  [0.64055146 0.08406808 0.96756192]
  [0.23315301 0.09738149 0.79044496]]

 [[0.67468264 0.72308617 0.36511593]
  [0.64618887 0.0422473  0.82699999]
  [0.34485573 0.14354272 0.37181846]]

 [[0.11501163 0.56360095 0.19364126]
  [0.27918443 0.9812059  0.64791645]
  [0.00345889 0.21872387 0.29431098]]]
[[[0.62170038 0.48133945 0.44290467]
  [0.71226804 0.86749867 0.40453865]
  [0.76455194 0.48523295 0.32472704]]

 [[0.02505261 0.27536659 0.01137675]
  [0.52372581 0.60779022 0.01660089]
  [0.89470596 0.52789764 0.6465182 ]]

 [[0.33201468 0.29664021 0.40126694]
  [0.55480823 0.17136762 0.19592999]
  [0.09217362 0.34570167 0.3216326 ]]]


In [26]:
#8. Normalize a random 5x5 matrix (values between 0 and 1).
#Hint: Normalize with (x - min) / (max - min)

a = np.random.random((5,5))
normalized_a = (a - a.min())/(a.max()-a.min())
print(normalized_a)

[[0.96435081 0.33384799 0.21571247 0.68005348 0.8050647 ]
 [0.22442366 1.         0.47037459 0.84417081 0.6741325 ]
 [0.45081293 0.16539516 0.23074694 0.87977997 0.5390226 ]
 [0.04431614 0.53783684 0.86618597 0.50789402 0.3133883 ]
 [0.12287888 0.         0.70551839 0.18242569 0.12658978]]


In [33]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (dot product).
#Hint: Use np.dot() or @

a = np.arange(0,15).reshape(5,3)
b = np.arange(0,6).reshape(3,2)
print(f'method 1 = {np.dot(a,b)}')
# Or also following works
print(f'method 1 = {a@b}')

method 1 = [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
method 1 = [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
